service:
  api:
    build: .
    ports:
      - "8000:8000"
    networks:
      - api-network
      - easypanel
    labels:
      - traefik.enable=true
      - traefik.docker.network=easypanel  # Importante: especificar a rede do Traefik
      - traefik.http.services.salf-api.loadbalancer.server.port=8000
      - traefik.http.routers.salf-api.entrypoints=websecure
      - traefik.http.routers.salf-api.tls=true
      - traefik.http.routers.salf-api.tls.certresolver=letsencrypt  # Se estiver usando Let's Encrypt
    networks:
      api-network:
        drive: bridge
      easypanel:
        external: true
